spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 111111
    url: jdbc:mysql://139.196.113.199:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: root
    password: root
    host: 139.196.113.199
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 139.196.113.199
    database: 0
    port: 6379
    password: 111111
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://139.196.113.199/